dev:
  name:
  user:
  password:
  host: localhost
  grant_to: localhost

staging:
  name:
  user:
  password:
  host:
  grant_to:
  # "grant_to" is the name of the server that will be requesting access
  # to the database, if you're using a separate DB server.
  # This should probably just be localhost.

production:
  name:
  user:
  password:
  host:
  grant_to: