application:
  name: projectname
  repo: git://github.com/username/projectname.git
  deploy_user: deploy
  user: projectuser
  access_users: [deploy, projectuser, user1, user2, user3]
  group: group

  theme: themename
  domain: domain.com
  tbl_prefix: wp_

  servers:
    dev:
      ip: 127.0.0.1
      http_port: 8080
      port: 2222
      user: vagrant
    staging:
      ip: 0.0.0.0
      port: 0
      user: deploy
    production:
      ip: 0.0.0.0
      port: 0
      user: deploy
